import os
import pathlib
from datetime import datetime

# ================================
# CONFIGURATION
# ================================

# Root directory to scan (current folder by default)
ROOT_DIR = pathlib.Path('.')

# Output file
OUTPUT_FILE = 'all_code.txt'

# File extensions to include
INCLUDE_EXT = {
    '.ts', '.tsx', '.js', '.jsx',
    '.css', '.scss', '.html', '.json',
    '.md', '.txt', '.yml', '.yaml',
    '.env.example', '.dockerfile', 'Dockerfile'
}

# Directories to SKIP
SKIP_DIRS = {
    'node_modules',
    'build', 'dist', '.git', '.next',
    '__pycache__', '.venv', 'venv'
}

# Files to SKIP
SKIP_FILES = {
    'package-lock.json',
    'yarn.lock',
    'npm-debug.log',
    '.DS_Store',
    'Thumbs.db'
}

# ================================
# SCRIPT
# ================================

def should_include(path: pathlib.Path) -> bool:
    """Return True if file should be included."""
    if path.name in SKIP_FILES:
        return False
    if path.suffix.lower() not in INCLUDE_EXT:
        return False
    if any(part in SKIP_DIRS for part in path.parts):
        return False
    return True

def main():
    root = ROOT_DIR.resolve()
    output_path = root / OUTPUT_FILE

    print(f"Scanning: {root}")
    print(f"Output: {output_path}")
    print(f"Looking for: {', '.join(INCLUDE_EXT)}")
    print("-" * 50)

    with open(output_path, 'w', encoding='utf-8') as out:
        out.write(f"# CODE DUMP - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        out.write(f"# Project: {root.name}\n")
        out.write(f"# Generated by copy_code_to_txt.py\n\n")
        out.write("="*80 + "\n\n")

        file_count = 0

        # Walk through all files
        for file_path in root.rglob('*'):
            if file_path.is_file() and should_include(file_path):
                rel_path = file_path.relative_to(root)
                print(f"Adding: {rel_path}")

                # Write file header
                out.write(f"--- FILE: {rel_path} ---\n")
                out.write(f"# Path: {file_path}\n")
                out.write(f"# Size: {file_path.stat().st_size} bytes\n\n")

                # Write file content
                try:
                    with open(file_path, 'r', encoding='utf-8') as f:
                        content = f.read()
                    out.write(content)
                except UnicodeDecodeError:
                    out.write("# [WARNING: Binary or non-UTF8 file - content skipped]\n")
                except Exception as e:
                    out.write(f"# [ERROR reading file: {e}]\n")

                out.write("\n\n" + "-"*80 + "\n\n")
                file_count += 1

        out.write(f"\n# TOTAL FILES COPIED: {file_count}\n")
        out.write(f"# Finished at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")

    print(f"\nDone! {file_count} files copied to {OUTPUT_FILE}")

if __name__ == '__main__':
    main()