export const meta = {
  name: 'country-wave-batch',
  description: 'Wave 1 in batches under the per-turn web search cap: reuse finished results, stop new work before the cap, continue in the next batch',
  phases: [
    { title: 'Discover', detail: 'Sonnet workers screen 30 categories plus country-specific ones and list every candidate' },
    { title: 'Critique', detail: 'Sonnet critic names missing categories (large countries)' },
    { title: 'Gap fill', detail: 'Sonnet researches not-reached categories and the critic gaps' },
    { title: 'Triage', detail: 'Sonnet merges duplicates and marks ideas the study already has' },
    { title: 'Verify', detail: 'Opus checks candidates scored 4+, Sonnet checks 3s; Sonnet 4+ escalates to Opus' },
    { title: 'Challenge', detail: 'an adversarial Opus check on every lead at 4+' },
  ],
}

// Generated by wave_state.py from this template and workflow.js: PRE holds every finished, unblocked result by label
// from earlier runs and batches, so a batch only runs what is still missing.
// args: { batch: 'b1', cap: 190, items: [{ id, name, stratum, shadow }] }
const PRE = /*__PRE__*/{}
/*__CONSTANTS__*/
/*__SCHEMAS__*/
const LEDGER2 = { ...LEDGER, required: [...LEDGER.required, 'blocked_searches'], properties: { ...LEDGER.properties, blocked_searches: num } }
const VERDICT2 = { ...VERDICT, required: [...VERDICT.required, 'searches', 'blocked_searches'], properties: { ...VERDICT.properties, searches: num, blocked_searches: num } }
const CHALLENGE2 = { ...CHALLENGE, required: [...CHALLENGE.required, 'searches', 'blocked_searches'], properties: { ...CHALLENGE.properties, searches: num, blocked_searches: num } }
const BLOCKED_NOTE = `\nIf a WebSearch call returns "Web search was not performed", stop searching, count those calls in blocked_searches, and return what you have, with anything you couldn't check marked not_reached or unverifiable.`
// Expected searches per agent, used to keep each batch under the per-turn cap.
const EST = { large: { A: 26, B: 22 }, medium: { A: 18, B: 16 }, small: { ALL: 20 }, GAPS: 16, verify: 6, challenge: 8 }
const { batch, cap: CAP, items } = args
/*__HELPERS__*/
/*__TIER0__*/

let used = 0
let reserved = 0
let blockedAt = null
const inflight = new Set()
const SKIP = { __skipped: true }
const isSkip = (r) => !r || r.__skipped === true
// A searching agent: reuse a finished result, or run it if the batch's search budget allows.
const live = async (label, prompt, phase, model, effort, schema, est) => {
  if (PRE[label]) return PRE[label]
  while (!blockedAt && used + reserved + est > CAP && inflight.size) await Promise.race([...inflight])
  if (blockedAt || used + reserved + est > CAP) return SKIP
  reserved += est
  const p = agent(prompt, { label: `${label}@${batch}`, phase, agentType: 'general-purpose', model, effort, schema })
  const settled = p.then(() => null, () => null)
  inflight.add(settled)
  const r = await p.catch(() => null)
  inflight.delete(settled)
  reserved -= est
  used += r && typeof r.searches === 'number' ? r.searches : est
  if (r && r.blocked_searches > 0) {
    if (!blockedAt) { blockedAt = label; log(`Search cap reached at ${label}: no new work in this batch`) }
    return SKIP
  }
  return r
}
const retry = (f) => f().then((r) => (r === null ? f() : r))  // an agent that died: once more
// A tool-free stage: no searches, so it never waits on the budget.
const desk = async (label, prompt, phase, schema) => {
  if (PRE[label]) return PRE[label]
  return agent(prompt, { label: `${label}@${batch}`, phase, model: 'sonnet', effort: 'medium', schema }).catch(() => null)
}

const runCountry = async (it) => {
  const cap = CAPS[it.stratum]
  const parts = it.stratum === 'small' ? ['ALL'] : ['A', 'B']
  const disc = (part, effort, tag) => retry(() => live(`${tag}:${part}:${it.id}`, brief(it, part) + BLOCKED_NOTE, 'Discover', 'sonnet', effort, LEDGER2, EST[it.stratum][part]))
    .then((r) => (isSkip(r) ? null : { ...r, part, tag }))
  const runs = await parallel(parts.map((p) => () => disc(p, 'high', 'discover'))
    .concat(it.shadow ? parts.map((p) => () => disc(p, 'medium', 'shadow')) : []))
  if (runs.some((r) => !r)) return { id: it.id, complete: false, stage: 'discovery' }
  const main = runs.slice(0, parts.length)
  const shadow = runs.slice(parts.length)

  // Critique (large countries) and the Tier 0 coverage check (all countries).
  let gaps = parts.flatMap((p, i) => coverageGaps(main[i], p))
  let criticGaps = null
  if (it.stratum === 'large') {
    const coverage = main.flatMap((r) => r.coverage.map((c) => ({ category: c.category, status: c.status, found: (c.found || '').slice(0, 160) })))
    const ledger = main.flatMap((r) => r.candidates.map((c) => ({ name: c.name, category: c.category, status: c.status, score: c.score, known: c.known_mark })))
    const g = await desk(`critic:${it.id}`, `${DEFINITIONS}\n${RUBRIC.critic}\n<country>${it.name}. Country file with the <known> list: ${countryFile(it)}</country>\n<coverage>\n${json(coverage)}\n</coverage>\n<ledger>\n${json(ledger)}\n</ledger>`, 'Critique', GAPS)
    if (!g) return { id: it.id, complete: false, stage: 'critique' }  // retried next batch, so later stages never use a stale gap list
    gaps = gaps.concat(g.gaps)
    criticGaps = g.gaps.length
  }
  gaps = uniqueGaps(gaps)

  // Gap fill: not-reached categories always; the critic's gaps for large countries.
  let extra = null
  if (gaps.length) {
    const r = await retry(() => live(`gapfill:${it.id}`, `${brief(it, 'GAPS')}\n<gaps>\n${json(gaps)}\n</gaps>\n${RUBRIC.gapfill}${BLOCKED_NOTE}`, 'Gap fill', 'sonnet', 'high', LEDGER2, EST.GAPS))
    if (isSkip(r)) return { id: it.id, complete: false, stage: 'gap fill' }
    extra = { ...r, part: 'GAPS', tag: 'gapfill' }
  }

  // Triage: ids assigned in code, high-effort ledgers first so merges keep them.
  const sources = main.concat(extra ? [extra] : [], shadow)
  const all = sources.flatMap((s) => s.candidates.map((c, j) => ({ ...c, id: `${s.tag === 'shadow' ? 'S' : ''}${s.part}${j + 1}`, src: s.tag })))
  const open = all.filter((c) => c.status !== 'rejected')
  const view = open.map((c) => ({ id: c.id, name: c.name, category: c.category, buyer: c.buyer, trigger: (c.trigger || '').slice(0, 300),
    score: c.score, status: c.status, known_mark: c.known_mark, known_id: c.known_id, known_note: c.known_note }))
  const t = await desk(`triage:${it.id}`, `${DEFINITIONS}\n${RUBRIC.triage}\n<country>${it.name}. Country file with the <known> list: ${countryFile(it)}</country>\n<candidates>\n${json(view)}\n</candidates>`, 'Triage', TRIAGE)
  if (!t) return { id: it.id, complete: false, stage: 'triage' }
  const decisions = t.decisions

  // Verify every new candidate scored 3+ (Opus for 4+, Sonnet for 3), escalate Sonnet 4+, challenge every 4+.
  const dec = new Map((decisions || []).map((d) => [d.id, d]))
  const ids = new Set(open.map((c) => c.id))
  const skip = (c) => {
    if (!decisions) return c.known_mark === 'known' ? 'known' : null    // triage failed: trust the worker's marks
    const d = dec.get(c.id)
    if (!d) return null                                                 // no decision: fail open
    if (d.decision === 'merge' && ids.has(d.ref) && d.ref !== c.id) return 'merged'
    if (d.decision === 'drop') return 'dropped'
    if (d.decision === 'known' && c.known_mark === 'known') return 'known' // both stages agree
    return null
  }
  const kept = open.filter((c) => !skip(c))
  const mergedInto = (c) => open.filter((o) => skip(o) === 'merged' && dec.get(o.id).ref === c.id)
  // A candidate the worker called known but triage kept as new has no score yet: check it at 3.
  const scoreOf = (c) => Math.max(c.score || 0, ...mergedInto(c).map((m) => m.score || 0), c.known_mark === 'known' ? 3 : 0)
  const rank = { unverified: 0, promising: 1, weak: 2 }
  const eligible = kept.filter((c) => scoreOf(c) >= 3)
    .sort((a, b) => scoreOf(b) - scoreOf(a) || (rank[a.status] || 0) - (rank[b.status] || 0))
  const high = eligible.filter((c) => scoreOf(c) >= 4)
  const opusQueue = high.slice(0, cap.opus)
  const sonnetQueue = high.slice(cap.opus).concat(eligible.filter((c) => scoreOf(c) < 4)).slice(0, cap.sonnet)
  const overflow = eligible.filter((c) => !opusQueue.includes(c) && !sonnetQueue.includes(c))
  const claimOf = (c) => ({ name: c.name, category: c.category, buyer: c.buyer, trigger: c.trigger, evidence: c.evidence,
    existing: c.existing, provisional_score: scoreOf(c), unchecked: c.unchecked, known_mark: c.known_mark, known_id: c.known_id,
    known_note: c.known_note, also_reported: mergedInto(c).map((m) => ({ name: m.name, evidence: m.evidence, existing: m.existing })) })
  const check = (c, model, tag) => retry(() => live(`${tag}:${it.id}:${c.id}`, `${DEFINITIONS}\n${RUBRIC.verify}${BLOCKED_NOTE}\n<country>${it.name}</country>\n<claim>\n${json(claimOf(c))}\n</claim>`,
    'Verify', model, 'medium', VERDICT2, EST.verify))
  const challenge = (c, first) => retry(() => live(`challenge:${it.id}:${c.id}`, `${DEFINITIONS}\n${RUBRIC.adversarial}${BLOCKED_NOTE}\n<country>${it.name}</country>\n<claim>\n${json(claimOf(c))}\n</claim>\n<first_check>\n${json({ score: first.suggested_score, competitor: first.competitor || '', sources: first.sources || '' })}\n</first_check>`,
    'Challenge', 'opus', 'medium', CHALLENGE2, EST.challenge))
  const atLeast4 = (v) => !isSkip(v) && v.verdict !== 'refuted' && v.suggested_score >= 4
  const withChallenge = (c, o, s) => atLeast4(o) ? challenge(c, o).then((ch) => ({ c, sonnet: s, opus: o, challenge: ch })) : { c, sonnet: s, opus: o, challenge: null }
  const thunks = opusQueue.map((c) => () => check(c, 'opus', 'opus').then((o) => withChallenge(c, o, null)))
    .concat(sonnetQueue.map((c) => () => check(c, 'sonnet', 'sonnet').then((s) =>
      atLeast4(s) ? check(c, 'opus', 'escalate').then((o) => withChallenge(c, o, s)) : { c, sonnet: s, opus: null, challenge: null })))
  const checked = (await parallel(thunks)).filter(Boolean)
  const pending = (x) => [x.sonnet, x.opus, x.challenge].some((v) => v && v.__skipped)
  const final = (x) => {
    if (pending(x)) return 'pending'
    if (!x.opus && !x.sonnet) return 'check_failed'
    const first = x.opus || x.sonnet
    if (first.verdict === 'refuted') return 'refuted'
    if (!atLeast4(first)) return first.verdict === 'unverifiable' ? 'unverifiable' : 'below_4'
    if (!x.opus) return 'escalation_failed'
    if (!x.challenge) return 'single_check_4'
    if (x.challenge.verdict === 'refuted') return 'refuted_on_challenge'
    return x.challenge.verdict === 'survives' && x.challenge.suggested_score >= 4 ? 'verified_4' : 'disputed'
  }
  const score = (v) => (v && !v.__skipped ? v.suggested_score : null)
  const rows = checked.map((x) => ({ id: x.c.id, name: x.c.name, src: x.c.src, mark: x.c.known_mark, prov: scoreOf(x.c),
    sonnet: score(x.sonnet), opus: score(x.opus), challenge: x.challenge && !x.challenge.__skipped ? `${x.challenge.verdict} ${x.challenge.suggested_score}` : null, final: final(x) }))
  const complete = checked.length === thunks.length && !checked.some(pending)
  return {
    id: it.id, complete, stage: complete ? 'done' : 'checks',
    candidates: all.length, gaps: gaps.length, criticGaps, triage: decisions ? count(decisions, (d) => d.decision) : 'failed',
    checks: { opus: opusQueue.length, sonnet: sonnetQueue.length, unverifiedByCap: overflow.map((c) => `${c.id} ${c.name}`) },
    finals: count(rows, (x) => x.final),
    leads: rows.filter((x) => ['verified_4', 'disputed', 'single_check_4', 'refuted_on_challenge', 'escalation_failed'].includes(x.final)),
  }
}

// Depth-first: finish one country before starting the next, so a stopped batch leaves whole countries done.
const out = []
for (const it of items) {
  if (blockedAt) { out.push({ id: it.id, complete: false, stage: 'not started' }); continue }
  out.push(await runCountry(it).catch((e) => ({ id: it.id, complete: false, stage: `error: ${e.message}` })))
}
log(`batch ${batch}: about ${used} searches; ${out.map((r) => `${r.id} ${r.complete ? 'done' : r.stage}`).join(', ')}`)
return { batch, used, blockedAt, countries: out }
